runtime: python39
api_version: 1
service: default
threadsafe: true

handlers:
  - url: /
    static_files: Front-End/index.html
    upload: Front-End/index.html

  - url: /(.*)
    static_files: Front-End/\1
    upload: Front-End/(.*)
